# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

resources:
  repositories:
  - repository: dtstrepro
    type: github
    endpoint: dts20180051
    name: dmittal01/dt2018005
    ref: refs/heads/main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
